"""empty message

Revision ID: 0e09c9d5f62b
Revises: 
Create Date: 2019-02-20 18:34:26.613586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e09c9d5f62b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_neighbor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msisdn', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('fcm_id', sa.String(length=255), nullable=True),
    sa.Column('fcm_token', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('record_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('msisdn')
    )
    op.create_table('tbl_sms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('msisdn', sa.String(length=20), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('record_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('record_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_neighbor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_neighbor_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('neighbor_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['tbl_group.id'], ),
    sa.ForeignKeyConstraint(['neighbor_id'], ['tbl_neighbor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_neighbor_group')
    op.drop_table('tbl_group')
    op.drop_table('tbl_token')
    op.drop_table('tbl_sms')
    op.drop_table('tbl_neighbor')
    # ### end Alembic commands ###
